#!/bin/sh

### test – Run the testsuite for Kaputt

# Kaputt (https://github.com/michipili/cl-kaputt)
# This file is part of Kaputt
#
# Copyright © 2019–2020 Michaël Le Barbier
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

sbcl --noinform --disable-debugger\
     --eval '(ql:quickload :kaputt/test :silent t)'\
     --eval '(if (kaputt/test:run-all-tests)(uiop:quit 0)(uiop:quit 1))'

### End of file `test'
